service: poc-node
provider: 
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  timeout: 30
  stage: v1
  endpointType: regional
  region: us-east-1
functions:
  api:
    handler: app.handler
    events:
      - httpApi: 'GET /accounts/{accountId}'
      